In [1]:
import pandas as pd

In [6]:
marathons = pd.read_csv('./data/marathonproject.csv')

In [7]:
marathons.head()

,Question #2,2016 Half,2016 Full,2017 Half,2017 Full,2018 Half,2018 Full,2019 Half,2019 Full,Combined Half,...,Column16364,Column16365,Column16366,Column16367,Column16368,Column16369,Column16370,Column16371,Column16372,Column16373
0,Fastest Time,1:11:15,2:25:42,1:10:58,2:40:25,1:09:25,2:28:16,1:10:03,2:34:59,4:41:41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Slowest Time,4:54:41,7:00:00,6:18:24,6:38:19,4:48:06,6:34:41,5:03:35,6:43:55,21:04:46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Median,2:26:18,4:45:19,2:39:34,4:58:14,2:25:32,4:48:21,2:26:07,4:41:57,9:57:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mean,2:31:57,4:47:48,2:43:59,4:54:26,2:31:46,4:48:23,2:32:07,4:42:09,10:19:48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Question #3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
marathons.info

<bound method DataFrame.info of                    Question #2             2016 Half          2016 Full  \
0                 Fastest Time               1:11:15            2:25:42
1                 Slowest Time               4:54:41            7:00:00
2                       Median               2:26:18            4:45:19
3                         Mean               2:31:57            4:47:48
4                  Question #3                   NaN                NaN
5   # who beat Oprah, 4:29:20                  17892               1099
6             % who beat Oprah                  100%                37%
7                  Question #4                   NaN                NaN
8                   Lowest %25               0.08910            0.17570
9                   Median %50               0.10160            0.19814
10                     Top %75               0.11818            0.22362
11                 Question #5  2017 had bad weather                NaN
12                 Question #6                   NaN                NaN
13          Scott Wietcha Time                   NaN            2:25:42
14             Second Finisher                   NaN            2:34:43
15         Difference in Times                   NaN            0:09:01
16                       BONUS                   NaN                NaN
17                 First Place                   NaN     Scott Wietecha
18                Second Place                   NaN      Brian Shelton
19                 Third Place                   NaN  Christopher Capps

   2017 Half       2017 Full 2018 Half       2018 Full 2019 Half  \
0    1:10:58         2:40:25   1:09:25         2:28:16   1:10:03
1    6:18:24         6:38:19   4:48:06         6:34:41   5:03:35
2    2:39:34         4:58:14   2:25:32         4:48:21   2:26:07
3    2:43:59         4:54:26   2:31:46         4:48:23   2:32:07
4        NaN             NaN       NaN             NaN       NaN
5      17593             615     14902             758     13683
6        99%             25%      100%             36%      100%
7        NaN             NaN       NaN             NaN       NaN
8    0.09603         0.18715   0.08844         0.17562   0.08824
9    0.11081         0.20711   0.10106         0.20025   0.10147
10   0.12859         0.22412   0.11894         0.22478   0.11910
11       NaN             NaN       NaN             NaN       NaN
12       NaN             NaN       NaN             NaN       NaN
13   1:10:58         2:40:25   1:09:25         2:28:16   1:10:03
14   1:11:25         2:56:28   1:09:51         2:29:52   1:12:15
15       NaN         0:16:03       NaN         0:01:36       NaN
16       NaN             NaN       NaN             NaN       NaN
17   2:25:42  Scott Wietecha   2:40:25  Scott Wietecha   2:28:16
18   2:34:43    Ryan Regnier   2:56:28      Kevin Fink   2:29:52
19   2:38:43  Daniel Everett   3:00:55   Andrew Hodges   2:38:59

         2019 Full Combined Half  ... Column16364  Column16365  Column16366  \
0          2:34:59       4:41:41  ...         NaN          NaN          NaN
1          6:43:55      21:04:46  ...         NaN          NaN          NaN
2          4:41:57       9:57:31  ...         NaN          NaN          NaN
3          4:42:09      10:19:48  ...         NaN          NaN          NaN
4              NaN           NaN  ...         NaN          NaN          NaN
5              793           NaN  ...         NaN          NaN          NaN
6              39%           NaN  ...         NaN          NaN          NaN
7              NaN           NaN  ...         NaN          NaN          NaN
8          0.17217       0.29563  ...         NaN          NaN          NaN
9          0.19580       0.10374  ...         NaN          NaN          NaN
10         0.21909       0.12120  ...         NaN          NaN          NaN
11             NaN           NaN  ...         NaN          NaN          NaN
12             NaN           NaN  ...         NaN          NaN          NaN
13         2:34:59           NaN  ...         NaN          NaN          NaN
14         2:35:24           NaN  ...         NaN          NaN          NaN
15         0:00:25           NaN  ...         NaN          NaN          NaN
16             NaN           NaN  ...         NaN          NaN          NaN
17  Scott Wietecha       2:34:59  ...         NaN          NaN          NaN
18   Jordan Wilson       2:35:24  ...         NaN          NaN          NaN
19  Steelton Flynn       2:39:59  ...         NaN          NaN          NaN

    Column16367  Column16368  Column16369  Column16370  Column16371  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN
16          NaN          NaN          NaN          NaN          NaN
17          NaN          NaN          NaN          NaN          NaN
18          NaN          NaN          NaN          NaN          NaN
19          NaN          NaN          NaN          NaN          NaN

    Column16372  Column16373
0           NaN          NaN
1           NaN          NaN
2           NaN          NaN
3           NaN          NaN
4           NaN          NaN
5           NaN          NaN
6           NaN          NaN
7           NaN          NaN
8           NaN          NaN
9           NaN          NaN
10          NaN          NaN
11          NaN          NaN
12          NaN          NaN
13          NaN          NaN
14          NaN          NaN
15          NaN          NaN
16          NaN          NaN
17          NaN          NaN
18          NaN          NaN
19          NaN          NaN

[20 rows x 16384 columns]>

In [10]:
marathons.columns

Index(['Question #2', '2016 Half', '2016 Full', '2017 Half', '2017 Full',
       '2018 Half', '2018 Full', '2019 Half', '2019 Full', 'Combined Half',
       ...
       'Column16364', 'Column16365', 'Column16366', 'Column16367',
       'Column16368', 'Column16369', 'Column16370', 'Column16371',
       'Column16372', 'Column16373'],
      dtype='object', length=16384)

In [11]:
marathons['2016 Half'].value_counts()

2016 Half
1:11:15                 1
4:54:41                 1
2:26:18                 1
2:31:57                 1
17892                   1
100%                    1
0.08910                 1
0.10160                 1
0.11818                 1
2017 had bad weather    1
Name: count, dtype: int64

In [12]:
type(2016 Half)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3331368559.py, line 1)

In [16]:
marathons.plot(kind='bar',
              x ='2016 Full',
              y ='2016 Half');

TypeError: no numeric data to plot